/**
 * Shapes of the vendored WHO Child Growth Standards reference tables.
 *
 * Hand-written (unlike the `*.data.ts` modules that use them, which are
 * generated by `scripts/convert-who-tables.ts`) so the generator and the
 * consumers agree on one definition. See `README.md` for provenance and
 * licensing of the underlying data.
 */

/**
 * One (sex, age) cell of a WHO LMS table: the Box-Cox power `l`, the median
 * `m` and the coefficient of variation `s`. Units of `m` follow the upstream
 * files — kilograms for weight, centimetres for length/height and head
 * circumference — NOT this app's internal base units (grams/millimetres);
 * `growth-percentiles.ts` converts before evaluating.
 */
export interface LmsPoint {
  ageInDays: number;
  l: number;
  m: number;
  s: number;
}

/** A per-sex indicator table with a single age axis (weight, head circumference). */
export interface IndicatorTable {
  male: LmsPoint[];
  female: LmsPoint[];
}

/**
 * The body-measure indicator, which WHO splits into recumbent `length`
 * (0–730 days) and standing `height` (731–1826 days) — see W-17.
 */
export interface BodyMeasureTable {
  male: { length: LmsPoint[]; height: LmsPoint[] };
  female: { length: LmsPoint[]; height: LmsPoint[] };
}

/** Attribution metadata embedded in every generated data module. */
export interface ReferenceDataProvenance {
  sourceUrl: string;
  sourceFile: string;
  retrievedOn: string;
  license: string;
  citation: string;
}
