/**
 * Registers the service worker generated by `vite-plugin-pwa`'s
 * `generateSW` strategy (`/sw.js`, emitted at build time next to
 * `manifest.webmanifest` — see vite.config.ts and
 * docs/adr/0008-pwa-basics-via-vite-plugin-pwa.md).
 *
 * Deliberately a plain function called once from `main.tsx` at module
 * scope, not a React `useEffect` — registration must happen exactly once
 * per page load regardless of React StrictMode's double-invocation of
 * effects in development, and has no reason to be tied to any component's
 * lifecycle. `injectRegister: false` on the Vite plugin means no
 * auto-injected registration script exists, so this is the only thing that
 * calls `navigator.serviceWorker.register(...)`.
 *
 * No-ops (rather than throwing) in two cases:
 * - not a production build (`import.meta.env.PROD` is false) — there is no
 *   `/sw.js` to register in dev, since the plugin only emits it at build
 *   time.
 * - `navigator.serviceWorker` isn't available (older/non-supporting
 *   browsers) — feature-detected rather than assumed.
 *
 * A registration failure is logged, not thrown, since the app must remain
 * fully usable without a service worker (this slice only adds offline
 * app-shell caching, nothing the app depends on to function).
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD) {
    return;
  }

  if (!('serviceWorker' in navigator)) {
    return;
  }

  navigator.serviceWorker.register('/sw.js').catch((error: unknown) => {
    console.error('Service worker registration failed', error);
  });
}
