/* GENERATED FILE — do not edit by hand. Run 'bun run design-tokens:build' to regenerate. Source: design-system/tokens/*.json */

/**
 * Design tokens in the units `@react-pdf/renderer` understands: colors as
 * literal hex (light values only — a printed page has no dark mode) and every
 * length as a bare number of PostScript points.
 *
 * Consumed by `styles.ts`, which is what actually calls `StyleSheet.create`.
 */
export const reportTokens = {
  color: {
    background: '#ffffff',
    foreground: '#1f2933',
    card: '#ffffff',
    'card-foreground': '#1f2933',
    popover: '#ffffff',
    'popover-foreground': '#1f2933',
    primary: '#4f46e5',
    'primary-foreground': '#ffffff',
    secondary: '#f1f5f9',
    'secondary-foreground': '#1f2933',
    muted: '#f1f5f9',
    'muted-foreground': '#64748b',
    accent: '#f1f5f9',
    'accent-foreground': '#1f2933',
    success: '#16a34a',
    'success-foreground': '#052e16',
    warning: '#d97706',
    'warning-foreground': '#451a03',
    destructive: '#dc2626',
    'destructive-foreground': '#ffffff',
    border: '#e2e8f0',
    input: '#e2e8f0',
    ring: '#4f46e5',
    feeding: '#f59e0b',
    'feeding-foreground': '#000000',
    'feeding-breast': '#ec4899',
    'feeding-breast-foreground': '#000000',
    'feeding-bottle': '#3b82f6',
    'feeding-bottle-foreground': '#000000',
    'feeding-solid': '#f97316',
    'feeding-solid-foreground': '#000000',
    sleep: '#8b5cf6',
    'sleep-foreground': '#000000',
    diaper: '#0d9488',
    'diaper-foreground': '#000000',
    'diaper-pee': '#eab308',
    'diaper-pee-foreground': '#000000',
    'diaper-stool': '#a16207',
    'diaper-stool-foreground': '#ffffff',
    'diaper-both': '#0d9488',
    'diaper-both-foreground': '#000000',
    'growth-weight': '#4338ca',
    'growth-length': '#047857',
    'growth-head-circumference': '#a21caf',
    'growth-band': '#4338ca',
    'milestone-motor': '#4338ca',
    'milestone-motor-foreground': '#ffffff',
    'milestone-language': '#0f766e',
    'milestone-language-foreground': '#ffffff',
    'milestone-social': '#d97706',
    'milestone-social-foreground': '#000000',
    'milestone-physical': '#be123c',
    'milestone-physical-foreground': '#ffffff',
  },
  spacing: {
    0: 0,
    1: 3,
    2: 6,
    3: 9,
    4: 12,
    5: 15,
    6: 18,
    8: 24,
    10: 30,
    12: 36,
    16: 48,
    'home-sidebar': 255,
  },
  radii: {
    sm: 3,
    md: 6,
    lg: 9,
    full: 7499.25,
  },
  fontSize: {
    xs: 9,
    sm: 10.5,
    base: 12,
    lg: 13.5,
    xl: 15,
    '2xl': 18,
    '3xl': 22.5,
  },
  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
  },
  fontWeight: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  fontFamily: {
    sans: 'system-ui, Avenir, Helvetica, Arial, sans-serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    report: 'Inter',
  },
} as const;

export type ReportTokens = typeof reportTokens;
